variables:
  CICD_SCRIPTS_DIR: "automation/cicd"
  # test line      

stages:
  - Generate and Validate TF Files
  - Plan and Apply in AWS
  - Provision
  - Permissions

# Templates
.docker_terraform:
  image:
    name: deiverk/ubuntu_terraform_python3:latest
    entrypoint: [""]
  only:
    refs:
      - /^((feature/.*))$/
      - /^((develop/.*))$/

# Jobs
# Initial job
Validate Terraform files:
  extends: .docker_terraform
  stage: Generate and Validate TF Files
  tags:
    - docker
  script:
    - ${CICD_SCRIPTS_DIR}/generate_validate_tf_files.sh
  cache:
    paths:
      - terraform/*.tf
  only:
    changes:
      - terraform/**/*
      - automation/cicd/.gitlab-ci.yml
      - automation/cicd/generate_validate_tf_files.sh
      - automation/cicd/terraform-pre-run.py

# Preparation
Plan and Apply in AWS:
  extends: .docker_terraform
  stage: Plan and Apply in AWS
  tags:
    - docker
  cache:
    paths:
      - terraform/*.tf
  script:
    - ${CICD_SCRIPTS_DIR}/plan_apply_in_aws.sh
  only:
    changes:
      - terraform/**/*
      - automation/cicd/.gitlab-ci.yml
      - automation/cicd/plan_apply_in_aws.sh


configure_aws_config:
  stage: Prepare
  tags:
    - shell
  script:
    - pwd
    - ls
  only:
    refs:
      - develop
    changes:
      - gitlab-ci.yml