#variables:
#  WRK_PATH
#  CICD_SCRIPTS_DIR  

stages:
  - Prepare
  - Provision
  - Permissions

initial_job:
  tags:
    - shell
  script:
    - echo "Initial job ok... ${ID_SYSTEM}"

organization provision:
  image:
    name: hashicorp/terraform:full
    entrypoint: [""]
  tags:
    - docker
  script:
    - automation/cicd/main.sh
  only:
    refs:
      - develop

configure_aws_config:
  tags:
    - shell
  script:
    - pwd
    - ls
  only:
    refs:
      - develop
    changes:
      - gitlab-ci.yml