# Main config
organization:
  name: company_name
  default-zone: us-west-2
  multizone-security: true          # default true
  core-ou:
    - security:
        email: security_email
        encription: AES256
    - logarchive:
        email: logarchive_email
    - shared-services:
        email: sharedservice_email
        issue-management: true
        k8s-cluster: true
    - network:
        email: network_email
  sandbox-ou:
    - test1:
        email: test-account_email
    - test2:
        email: test-account-2_email