apiVersion: v1
kind: Service
metadata:
  name: eagleconsole
  labels:
    app: eagleconsole
spec:
  selector:
    app: eagleconsole
  ports:
    - port: 80
      targetPort: 4200
      name: http
    - port: 443
      targetPort: 4200
      name: https
  clusterIP: 172.20.0.1
  type: LoadBalancer
