apiVersion: v1
kind: Service
metadata:
  name: eagleconsole
  labels:
    app: eagleconsole
spec:
  ports:
    - port: 80
      targetPort: 4200
      name: http
    - port: 443
      targetPort: 4200
      name: https
  selector:
    app: eagleconsole