apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eagleconsole-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eagleconsole
        version: v1
    spec:
      containers:
        - name: eagleconsole
          image: gcr.io/tranquility-base-images/tb-eagle-console:landingzone
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 80
