apiVersion: v1
kind: Service
metadata:
  name: eagleconsole
  labels:
    app: eagleconsole
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
spec:
  selector:
    app: eagleconsole
  ports:
    - port: 80
      targetPort: 4200
      name: http
    - port: 443
      targetPort: 4200
      name: https
  type: LoadBalancer
