apiVersion: v1
kind: Service
metadata:
  name: houstonservice
  labels:
    app: houstonservice
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: http
    - port: 443
      targetPort: 3000
      name: https
  selector:
    app: houstonservice